version: '2'
services:

  campaign_test:
    build:
      context: ./campaign
      dockerfile: Dockerfile.test
    container_name: com.netsocks.test.campaign.api

  fan_test:
    build:
      context: ./associate_fan
      dockerfile: Dockerfile.test
    container_name: com.netsocks.test.associatefan.api

  stream_test:
    build:
      context: ./stream
    container_name: com.netsocks.test.stream
    command: ./gradlew check
