version: '2'

networks:
  app-tier:
    driver: bridge

services:
  campaign:
    build:
      context: ./campaign
    container_name: com.netsocks.campaign.api
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongo/netsocks_campaign
      - server.port=8080
    depends_on:
      - mongo
      - redis
    networks:
      - app-tier

  fan:
    build:
      context: ./associate_fan
    container_name: com.netsocks.associatefan.api
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - MONGO_URI=mongodb://mongo/netsocks_associatefan
      - CAMPAIGN_API_URL=http://campaign
      - server.port=8081
    depends_on:
      - mongo
    networks:
      - app-tier

  campaign_update_receiver:
    build:
      context: ./campaign_update_receiver
    container_name: com.netsocks.campaign.receiver
    restart: on-failure
    environment:
      - REDIS_URI=redis://redis
    depends_on:
      - redis
    networks:
      - app-tier

  mongo:
    image: mongo
    container_name: com.netsocks.mongodb
    restart: on-failure
    ports:
      - 27018:27017
    networks:
      - app-tier

  redis:
    image: redis
    container_name: com.netsocks.redis
    restart: on-failure
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
